//! Host HTTP file server — serves VERSION, /update scripts, and /bin/:filename
//! to Guest VMs. Replaces the old FTP server. Read-only, no upload/exec routes.
//! Uses std.http.Server from the Zig standard library. Thread-per-connection.

const std = @import("std");
const http = std.http;
const protocol = @import("protocol.zig");

/// Configuration for the Host HTTP file server
pub const Config = struct {
    port: u16 = protocol.DEFAULT_HTTP_PORT,
    serve_dir: []const u8,
    host_ip: ?[]const u8 = null, // For /update script generation
};

/// Start the HTTP server — runs in a loop, never returns
pub fn startServer(io: std.Io, gpa: std.mem.Allocator, config: Config) !void {
    const addr = try std.Io.net.IpAddress.parse("0.0.0.0", config.port);
    var listener = try addr.listen(io, .{});
    defer listener.close(io);

    std.debug.print("[host-http] Serving files from {s}/ on port {d}\n", .{ config.serve_dir, config.port });

    while (true) {
        const stream = listener.accept(io) catch |err| {
            std.debug.print("[host-http] Accept error: {}\n", .{err});
            continue;
        };

        // Spawn thread per connection
        const handle_thread = std.Thread.spawn(.{}, handleClient, .{ io, gpa, stream, config }) catch {
            std.debug.print("[host-http] Failed to spawn thread\n", .{});
            stream.close(io);
            continue;
        };
        handle_thread.detach();
    }
}

fn handleClient(io: std.Io, gpa: std.mem.Allocator, stream: std.Io.net.Stream, config: Config) void {
    defer stream.close(io);

    var read_buf: [65536]u8 = undefined;
    var write_buf: [4096]u8 = undefined;

    var reader = stream.reader(io, &read_buf);
    var writer = stream.writer(io, &write_buf);

    var server = http.Server.init(&reader.interface, &writer.interface);

    // Keep-alive loop
    while (true) {
        var request = server.receiveHead() catch |err| {
            if (err != error.HttpHeadersExceededSizeLimit) {
                // Client disconnected or invalid request
            }
            return;
        };

        dispatch(&request, io, gpa, config) catch |err| {
            std.debug.print("[host-http] Error handling request: {}\n", .{err});
        };

        if (!request.head.keep_alive) return;
    }
}

fn dispatch(request: *http.Server.Request, io: std.Io, gpa: std.mem.Allocator, config: Config) !void {
    const path = request.head.target;

    // GET /version
    if (request.head.method == .GET and std.mem.eql(u8, path, "/version")) {
        return handleVersion(request, io, gpa, config);
    }

    // GET /update
    if (request.head.method == .GET and std.mem.eql(u8, path, "/update")) {
        return handleUpdate(request, io, gpa, config);
    }

    // GET /bin/:filename
    if (request.head.method == .GET and std.mem.startsWith(u8, path, "/bin/")) {
        const filename = path["/bin/".len..];
        if (filename.len == 0) {
            try request.respond("Not Found\n", .{ .status = .not_found });
            return;
        }
        return handleBinDownload(request, io, config, filename);
    }

    // 404 for everything else
    try request.respond("Not Found\n", .{ .status = .not_found });
}

/// GET /version — return the VERSION file content
fn handleVersion(request: *http.Server.Request, io: std.Io, gpa: std.mem.Allocator, config: Config) !void {
    // Build path: serve_dir/VERSION
    var path_buf: [512]u8 = undefined;
    const ver_path = try std.fmt.bufPrint(&path_buf, "{s}/VERSION", .{config.serve_dir});

    const file = std.Io.Dir.cwd().openFile(io, ver_path, .{}) catch {
        try request.respond("utmm v" ++ protocol.VERSION ++ "\n", .{
            .status = .ok,
            .extra_headers = &.{
                .{ .name = "content-type", .value = "text/plain" },
            },
        });
        return;
    };
    defer file.close(io);

    const file_len = file.length(io) catch 0;
    const file_data = try gpa.alloc(u8, @intCast(file_len));
    defer gpa.free(file_data);
    _ = file.readPositional(io, &.{file_data}, 0) catch {};

    try request.respond(file_data, .{
        .status = .ok,
        .extra_headers = &.{
            .{ .name = "content-type", .value = "text/plain" },
        },
    });
}

/// GET /update — return the bootstrap shell script
fn handleUpdate(request: *http.Server.Request, io: std.Io, gpa: std.mem.Allocator, config: Config) !void {
    _ = io;

    const host_ip = config.host_ip orelse "127.0.0.1";
    const port = config.port;

    const script = try std.fmt.allocPrint(
        gpa,
        \\#!/bin/sh
        \\# utmm auto-update script (generated by Host HTTP server)
        \\set -e
        \\HOST="{s}"
        \\PORT="{d}"
        \\TARGET="/opt/utmm/utmm"
        \\echo "[update] Downloading from http://$HOST:$PORT/bin/utmm..."
        \\if command -v curl >/dev/null 2>&1; then
        \\  curl -fsSL "http://$HOST:$PORT/bin/utmm" -o "$TARGET.new"
        \\elif command -v wget >/dev/null 2>&1; then
        \\  wget -q "http://$HOST:$PORT/bin/utmm" -O "$TARGET.new"
        \\else
        \\  echo "[update] No curl or wget, cannot download"
        \\  exit 1
        \\fi
        \\chmod +x "$TARGET.new"
        \\mv "$TARGET.new" "$TARGET"
        \\echo "[update] Done. Restarting..."
        \\pkill utmm || true
        \\sleep 1
        \\"$TARGET" &
        \\
    , .{ host_ip, port });
    defer gpa.free(script);

    try request.respond(script, .{
        .status = .ok,
        .extra_headers = &.{
            .{ .name = "content-type", .value = "text/plain" },
        },
    });
}

/// GET /bin/:filename — serve a binary file from serve_dir
fn handleBinDownload(request: *http.Server.Request, io: std.Io, config: Config, filename: []const u8) !void {
    // Prevent path traversal
    if (std.mem.indexOfScalar(u8, filename, '/') != null or
        std.mem.indexOfScalar(u8, filename, '\\') != null)
    {
        try request.respond("Forbidden\n", .{ .status = .forbidden });
        return;
    }

    var path_buf: [512]u8 = undefined;
    const full_path = try std.fmt.bufPrint(&path_buf, "{s}/{s}", .{ config.serve_dir, filename });

    const file = std.Io.Dir.cwd().openFile(io, full_path, .{}) catch {
        try request.respond("Not Found\n", .{ .status = .not_found });
        return;
    };
    defer file.close(io);

    const file_len = file.length(io) catch 0;

    var resp_buf: [4096]u8 = undefined;
    var response = try request.respondStreaming(&resp_buf, .{
        .respond_options = .{
            .status = .ok,
            .extra_headers = &.{
                .{ .name = "content-type", .value = "application/octet-stream" },
                .{ .name = "cache-control", .value = "no-cache" },
            },
        },
    });

    var fbuf: [65536]u8 = undefined;
    var offset: u64 = 0;
    while (offset < file_len) {
        const to_read = @min(fbuf.len, file_len - offset);
        const n = file.readPositional(io, &.{fbuf[0..to_read]}, offset) catch break;
        if (n == 0) break;
        _ = try response.writer.writeVec(&.{fbuf[0..n]});
        offset += n;
    }
    try response.end();
    std.debug.print("[host-http] Served {s}: {} bytes\n", .{ filename, offset });
}
